export const FETCHED_OKRS = "FETCHED_OKRS";
export const TOGGLE_PARENT = "TOGGLE_PARENT";
export const SELECT_CATEGORY = "SELECT_CATEGORY";
export const FETCHING_OKRS_FAILED = "FETCHING_OKRS_FAILED";
